name: Build Vue
on: [push]
jobs: 
  build-vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      working-directory: './frontend'
      uses: xRealNeon/VuePagesAction@1.0.0
      with:
        username: 'leo848'
        reponame: 'jufo2023'
        token: ${{ secrets.GITHUB_TOKEN }}
        gitname: Vue Builder
        gitmsg: Build Vue
